[package]
name = "Webserver"
version = "0.1.0"
authors = ["Raboliot le gris <jordan@raboland.fr>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket-multipart-form-data = "0.8.1"
nanoid = "0.3.0"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json", "serve", "tera_templates"]