[package]
name = "fractal"
version = "0.1.0"
authors = ["RaboliotLeGris <jordan@raboland.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15"
image = "0.22.3"
