[package]
name = "HumanTalks"
version = "0.1.0"
authors = ["Raboliot Le Gris <jordan@raboland.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"